### ISSUE TITLE
Cannot run version 1.1.0

### ISSUE THREAD

**Issue by beans-squared** [KoalaDevs/KoalaLauncher#109]
**Describe the bug**
When attempting to launch KL version 1.1.0, a error like shown under screenshots is produced.

**To Reproduce**
1. Run KoalaLauncher

**Expected behavior**
The app to launch and perform as normal.

**Possible solutions**
- Figuring out what is causing the issue
- Praying to the computer gods and maybe it fixes itself
- Bribing the computer with additional downloadable RAM
- ???

**Screenshots**
![image](https://user-images.githubusercontent.com/65502593/107128242-d5aeba80-6881-11eb-8c48-c88930006870.png)

**System Info:**
 - OS: Windows 10 Home
 - Koala Version: 1.1.0
 - CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.20 GHz
 - Video Card: GeForce 1050 Ti

**Additional context**
Update sounds lit, I just want to be able to see it :)

**Comment by Matows** [comment]
I'm having the same issue, except I'm installing for the first time.

**System Info:**

- OS: Windows 10 Pro
- Koala Version: 1.1.0
- CPU: AMZ Ryzen 7 3700X
- GPU: AMD Radeon RX 5600 XT

**Comment by rangicus** [comment]
Same issue. Worked flawlessly for the past few months.
