### ISSUE TITLE
if the changelog is dynamicly loaded, then we got some fixes

### ISSUE THREAD

**Issue by kreezxil** [KoalaDevs/KoalaLauncher#11]
![image](https://user-images.githubusercontent.com/3880072/94633519-250d2a80-0293-11eb-8520-716db1640c1e.png)
* remove the word `to` and replace it with a full stop `.` aka the period
* capitalize the letter m.
* profit.

**Comment by CrankySupertoon** [comment]
Its not dynamically loaded but that something i wanted done
