### ISSUE TITLE
/linkout can't be found

### ISSUE THREAD

**Issue by kreezxil** [KoalaDevs/KoalaLauncher#16]
![image](https://user-images.githubusercontent.com/3880072/95129912-59646900-0721-11eb-9b31-a2aadeb92a18.png)

I reported this issue to twitch a long time ago, guess it never got fixed. On cf pages when links appear that go outside the cf domain that are not authorized like youtube or github, a scrubber (that's what i'm calling it) is interjected "/linkout?" and this actually causes problems with launchers trying to use the same link.

This appears because kdl and gdl now support showing changelogs on mods inside the launchers. They need to sanitize the links so that this does not happen.

**Comment by kreezxil** [comment]
The problem is that the external launcher is not autorized to run the /linkout program on the curseforge site.

And in the case of Twitch, they had a user called Linkout, so ... Twitch would try to load the Linkout user.

**Comment by CrankySupertoon** [comment]
Mind giving an example i cannot duplicate

**Comment by TOLoneWolf** [comment]
This one has just /linkout without the cursefore url. Seems like curseforge started using their full url with linkout on the rest of their pages.  
https://www.curseforge.com/minecraft/modpacks/kreezcraft-presents-cobbleblock/files/2675026  
![image](https://user-images.githubusercontent.com/8376628/95662737-da937580-0afe-11eb-951c-1261d2776a98.png)
![image](https://user-images.githubusercontent.com/8376628/95662760-e3844700-0afe-11eb-8ab5-92b40e96de70.png)


This is how it was patched over in the old launcher when the linkout was different.  
https://github.com/CrankySupertoon/GDLauncher-Classic/commit/5ba5634a70edc077769413f5cd28f9babfd9728c

**Comment by CrankySupertoon** [comment]
Also the mod description page has it but not the Changelogs modal
