### ISSUE TITLE
Orphaned Processes

### ISSUE THREAD

**Issue by TOLoneWolf** [KoalaDevs/KoalaLauncher#18]
**Describe the bug**
Launcher fails to close all threads on close.
This issue showed up between version 1.0.0 to 1.0.2

**To Reproduce**
use any version greater then 1.0.0 
open launcher > close launcher > check task manager > see launchers child threads still open.

**Expected behavior**
No threads remaining open.

**System Info:**
 - OS: Windows
 - Koala Version: all versions > 1.0.0

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/98830903-8d0d6f80-2400-11eb-922b-93ae731233bf.png)

I wonder if that is why Windows users were getting their config.json's corrupted so often. Davide always said it was because a process was opening and writing to it as the possible cause.

**Comment by TOLoneWolf** [comment]
No it's not the same issue.... 
If you read when it happens.

Gel did have this awhile back though.

**Comment by TOLoneWolf** [comment]
building locally results in an exe that closes all threads properly after main window is closed.
locally using vs2017.

windows.yml

old working build config:  
`run: npm install --global --production --vs2015 --verbose windows-build-tools@4.0.0`  
`run: npm config set msvs_version 2015`  

current build config:  
`run: npm install --global --production --vs2019 windows-build-tools@4.0.0`  
`run: npm config set msvs_version 2019`  

switching back to vs2015 appears to fix this issue from tests.
