### ISSUE TITLE
mods view

### ISSUE THREAD

**Issue by kreezxil** [KoalaDevs/KoalaLauncher#23]
when searching for mods, when hovering a mod profile, the mod author should be displayed too. I think it would be helpful to also indicate if it is fabric or forge since the launcher already seems to know. Like maybe there is a white silohuette symbol of the forge for forge and the symbol but with a red slash thru it to indicate not forge ie fabric.

**Comment by CrankySupertoon** [comment]
Or maybe we could just do a forge icon, a fabric icon or something like that

**Comment by CrankySupertoon** [comment]
Its easier to detect if a mod is Fabric or Not Fabric not the other way around

**Comment by kreezxil** [comment]
Either way, you're the one neck deep in the code, having that little icon
would be really helpful.
