### ISSUE TITLE
linux taskbar icon

### ISSUE THREAD

**Issue by kreezxil** [KoalaDevs/KoalaLauncher#30]
![image](https://user-images.githubusercontent.com/3880072/97285223-f2ae0900-180f-11eb-86a0-ecacd92dafa1.png)

the changelog said you fixed it "hopefully", but all your changelogs say that. Maybe this is a bug for the changelog not changing.

![image](https://user-images.githubusercontent.com/3880072/97285379-2426d480-1810-11eb-98e1-a0023a580939.png)

**Comment by kreezxil** [comment]
the system tray icon isn't broken however. i don't think it ever was just in case you been trying to fix the wrong thing the whole time.

![image](https://user-images.githubusercontent.com/3880072/97286011-f9894b80-1810-11eb-8701-3b9b1856fbd3.png)

**Comment by CrankySupertoon** [comment]
Something broken on your machine. Report to electron builder
