### ISSUE TITLE
koala's changelog

### ISSUE THREAD

**Issue by kreezxil** [KoalaDevs/KoalaLauncher#31]
after you make the initial changelog goaway there appears to be no way to get it back. Perhaps  have this section of the general config show it if you click on the logo, or have the word "changelog" near the version and you can click that, or you can click the version number there to bring it up.

![image](https://user-images.githubusercontent.com/3880072/97285574-6223f880-1810-11eb-9b36-651ee19e028d.png)

**Comment by CrankySupertoon** [comment]
That already is an feature

**Comment by kreezxil** [comment]
where? how do i access it?
