### ISSUE TITLE
"Team Sync"

### ISSUE THREAD

**Issue by Rensik** [KoalaDevs/KoalaLauncher#39]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

The idea is: If a profile marked Master is shared between Koala Launchers then they sync up. At that point any changes to either transfer between them. If a profile being shared is marked as Secondary, then it only receives updates.

**Comment by Rensik** [comment]
Team Sync road-map: 
First, sync profiles. 
- Utilize CurseForge (further known as CF) for all DLs until a revenue system for devs* can be implemented.
Second, add a Secondary tag to limit editors vs users. 
Third, implement a revenue system for devs. 
- Any dev that signs up for KDL's revenue system(ads, subscriptions, w/e) must agree to allow KD Launchers(the program) to host and distribute their mods. This will hereby grant permission to KDL to torrent/sync files directly between Launchers and bypass CF entirely. 
Fourth: Implement a subscription system for users to turn off ads and still be able to generate revenue for devs.

* A 'dev' is anyone who creates and shares content through the KDL system.
- 'Content' is as follows, but not limited to, mods, mod packs, user-created images, video showcases, and etc.

**Comment by CrankySupertoon** [comment]
1) like from computer to computer? Guess that works but we need server space
2) I'm confused
3) Once again we need server space but I like the concept. I do not want to mirror mod devs files. Tons of curse Alternatives still exist and I don't want it to be us mirroring them. qI still thinks something more like APT Repositories is better. As in you have a list of Repositories and you can add them in. Essentially it's like the same thing ish. For example, if x modified ATM6 and wanted to release it. he could add it onto his personal repository and then the users can add it through add repositories. Then this can be accessed somewhere in the launcher. This would essentially be a JSON file linking to Curse ZIPs. We could also add additional metadata into the Curse ZIPs at a later date.
4) I do not want to add ads to the launcher. Ads will not be enough to pay mod devs.

**Comment by kreezxil** [comment]
why not have it be something like a torrent file, where the seed is what gets shared.

**Comment by CrankySupertoon** [comment]
I still think repository’s are safer and I don’t want to get into Illegal territory especially when we would already be redistributing mods which I already don’t want. And it’s not like people only download a torrent client to pirate games and movies. No one would ever do that
