### ISSUE TITLE
[Feature Request] Differential Update

### ISSUE THREAD

**Issue by kreezxil** [KoalaDevs/KoalaLauncher#40]
I think having a differential update will be advantageous to our launcher platform and will help to steal players away from Technic which has Solder (a differential update engine), as well as other launchers.

Based on that existing installed packs have a manifest and that packs hosted on cf have different (updated) copy of that manifest, this is my thoughts (oversimplified description incoming) of what the mechanics would look like.

A pack is updated, so the pack zip downloads per usual.

The json manifest from the updated pack is compared against the manifest from the installed pack.
- content missing from the updated manifest that used to be in the installed manifest is deleted (or archived).
- content that is new is added, and content that was marked as updated is updates < -- this last part is likely our current engine model.

The advantage of this would be same advantage that Technic Solder enabled mod packs enjoy but with the added bonus that all modpacks on cf would be able to enjoy it thru us with no need for Solder Server software.

Ok, you still don't get it.

Existing content that is neither removed or updated is not deleted and reinstalled and therefore not redownloaded. This will speed up updates times greatly.

**Comment by Rensik** [comment]
This is very much the first step to Stage 1 in my 'Team Sync' road map in my 'Team Sync' feature request. :+1:

**Comment by CrankySupertoon** [comment]
So essentially you want a folder somewhere to "cache" mods and instead of Downloading them you want to add them from said cache? 

@TOLoneWolf

**Comment by kreezxil** [comment]
when the pack updates
it doesn't delete the mods folder until it knows what is being updated or removed
ie don't delete the original manifest
you can compare that against the new manifest

the comparison should reveal what needs to be deleted, what needs to be updated, and what needs to be added.

**Comment by CrankySupertoon** [comment]
Ahh. Still thinking caching all mods will be good though.

**Comment by kreezxil** [comment]
why download when you don't need to tho.

doing this will kill Technic and I want very much to see that.

**Comment by CrankySupertoon** [comment]
I don’t understand. People only use Tekkit for piracy aka no mod dev permission

**Comment by TOLoneWolf** [comment]
Caching would speed it up a bunch but a compare and replace would be nicer.

The old pr I had made for caching would cover the download no problem. Made it use hard links even so less drive usage as more mods where alike in each pack.

**Comment by Rensik** [comment]
I remember ATLauncher doing this. They would only download mods that weren't in their local mods repository already. Once the mods were downloaded, any pack that called for a mod that was already there installed 10x faster.
