### ISSUE TITLE
Broken new instance name input

### ISSUE THREAD

**Issue by TOLoneWolf** [KoalaDevs/KoalaLauncher#48]
**Describe the bug**
Broken new instance name input.

**To Reproduce**
Make a new instance.
Type in a name. Like: "Vanilla 1.14.4"
See that the instance uses default name "Vanilla Minecraft" and not the one typed in. 

**Expected behavior**

**Possible solutions**

**Screenshots**

**System Info:**
 - OS: Winows 10 pro and Linux
 - Koala Version 1.0.8

**Comment by kreezxil** [comment]
confirmed.

found that if you hit back then forward you can forward past the name you entered.

**Comment by CrankySupertoon** [comment]
Fixed in 1.0.11
