### ISSUE TITLE
Version 1.0.11 Big Bugged

### ISSUE THREAD

**Issue by defranke00** [KoalaDevs/KoalaLauncher#88]
**Describe the bug**
After my client updated to the 1.0.11 version of KoalaLauncher, I have been having trouble downloading or updating modpacks. It currently will only reach 25% when download mods, then it stops. For a certain pack containing 220+ mods, it only downloaded 63 or so. With another pack with around 100 mods, it only downloaded 40 mods. At the time this started, I could still play packs through the launcher. It wouldn't even attempt to import a .zip file. If I tried to delete and instance it would just give the spinning ring of death. Would look like it was doing something, but would go for 10-20mins if left unchecked. Closing launcher and reopening shows it was successful, but on previous versions it was pretty quick. Downloading was also ridiculously slow when compared to previous versions.
The next thing I noticed was that whenever I would launch a pack, it would instantly crash (Not the launcher but the minecraft window) without a crash report being given (This was about a week ago). It then progressed to not even recognize me clicking the pack icon to launch the pack. I can sit and click it as many times as I feel up to, and it won't do anything. It discolors when you hover over it, just won't launch the pack. I can verify it isn't an instance issue was I can set the normal minecraft launcher directory to the instance and it works like new.
I also attempted to install just a vanilla version and non-modded forge version just as test installs. Vanilla seemed to work (I didn't actually play but it got to the home screen with Single player, Multi). Forge turns out, didn't even download any files for it, just created an instance without any files.
If I would uninstall 1.0.11 and reinstall 1.0.0 (I think, installer downloaded on 10/4/2020) It would function until it auto-updated back to 1.0.11 and the most recent problem would ensue.

**To Reproduce**
1. Install 1.0.0 from 10/4/2020 (I can upload the installer if necessary)
2a. Open and close KDL a few times until it auto-updates from 1.0.0 to 1.0.11
2b. Open and close KDL a few times until it auto-changes directories from Roaming/gdlauncher-next to Roaming/koalalauncher (not sure about this one, old KDL before all the troubles was in koalalauncher folder, not sure where the gdl-next is coming from)
3. Attempt to install different packs, check installed mods compared to known number of mods. (Its quite random too, its not like it only downloads a-f)
**Expected behavior**
Download desired Modpack version, Reasonable download time, download mods 100%
Click modpack icon, minecraft window opens, game begins to launch.

**Possible solutions**
Disabling Auto-Update so that users can remain on versions that work for them (Have not found an option like this, other than in the settings to update when I am on the 1.0.0 version)

**Screenshots**

**System Info:**
 - OS: Windows 10
 - Koala Version [e.g. 1.0.0]: 1.0.11
 - CPU: Intel i7-6700 HQ @ 2.6GHz, clocked to 3.2GHz
 - Video Card: Nvidia GeForce GTX 980M

Thank you for releasing this launcher. I have really enjoyed using this launcher, but it seems that I have just been fighting it for the last week or so. I hadn't played much from the launcher for a couple weeks before that, so I am not entirely sure when this may have started to happen, other than when I started using the launcher again.

**Comment by CrankySupertoon** [comment]
> 1. (not sure about this one, old KDL before all the troubles was in koalalauncher folder, not sure where the gdl-next is coming from)

Koala Launcher was a Fork of GDLauncher. We renamed the directory it stores files into in 1.0.2

**Comment by CrankySupertoon** [comment]
Honestly try deleting the userdata. Make sure to back it up first.

**Comment by defranke00** [comment]
No crash reports are generated when attempting to launch, but the latest.log is quite short and gives a little bit more information than the launcher crash shows. https://gist.github.com/defranke00/e12e9504223faeaed64b5483b42f41ff
![Crash](https://user-images.githubusercontent.com/63429962/102517177-5b1da780-4055-11eb-823f-5c1d992b57dc.PNG)
