### ISSUE TITLE
Not listing the mod I expected to see

### ISSUE THREAD

**Issue by Xelbayria** [KoalaDevs/KoalaLauncher#9]
- [X] I searched the issue tracker for other issues covering my case
- [X] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
When I am in "Mods browser" to find mods and add them. I was looking for "Had Enough Item" but I had to scroll down to find it.

**To Reproduce**
1. Right-Click the profile of minecraft and click "Manage" 
2. Go to "Mods" Tab (left side) and click "Add mods" (top, right side)
3. Type "Had Enough Items" in the search box 
4. Scroll down until you see "Had Enough Items" 

**Expected behavior**
I expected that the words are matched to the mod that it will be at the top of the list... not in middle of the list making me looking for it. 

**Possible solutions**
Try improve the search engine. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12866666/233889030-3177a531-c928-4b4f-a500-7f2939d1d3c7.png)

**Operating System:**
- OS: Windows 10 pro
- Launcher Version: v1.2.1
- Java Version: 8_362
- Minecraft Version: 1.12.2
- Mod Loader: Forge

**Additional context**
NONE

**Comment by furtabs** [comment]
CurseForge uses an AND search meaning it will search for had AND enough and ITEMS. Nothing we can fix

**Comment by Xelbayria** [comment]
> CurseForge uses an AND search meaning it will search for had AND enough and ITEMS. Nothing we can fix

Ah i don't know about that.  I am very familiar with `AND`, `OR`, `NOT`.  Thanks for telling me. I understand why you cannot fix this.
